# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2d45e8ab42260cbb284547fe8f89fd06"
name = "remixapp"
handle = "remixapp-34"
application_url = "https://word-americas-cuba-rug.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://word-americas-cuba-rug.trycloudflare.com/auth/callback",
  "https://word-americas-cuba-rug.trycloudflare.com/auth/shopify/callback",
  "https://word-americas-cuba-rug.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
